apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: deployments
  name: deployment-manager-role
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
